version: "3"
services:
  aws-deployment-test:
    image: 015776309570.dkr.ecr.us-east-2.amazonaws.com/ms-mn:latest 
    container_name: aws-deployment-test
    depends_on:
      - postgres
    environment:       
      PG_HOST: postgres    
  postgres:
    container_name: postgres
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages-manager
  sut:
    build: .
    depends_on:
      - aws-deployment-test
    environment:       
      SERVICE_HOST: aws-deployment-test    
    command: npm run test