version: "3"
services:
  aws-deployment-test:
    build: .
    environment:       
      PG_HOST: postgres    
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  sut:
    build: .
    environment:
      SERVICE_HOST: aws-deployment-test    
    command: npm run test