version: "3"
services:
  aws-deployment-test:
    container_name: aws-deployment-test
    # image: 403698577297.dkr.ecr.us-east-2.amazonaws.com/aws-deployment-test:latest 
    build: .
    depends_on:
      - postgres
    environment:       
      PG_HOST: postgres    
  postgres:
    container_name: postgres
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  sut:
    # image: 403698577297.dkr.ecr.us-east-2.amazonaws.com/aws-deployment-test:latest 
    build: .
    depends_on:
      - aws-deployment-test
    environment:
      SERVICE_HOST: aws-deployment-test    
    command: npm run test