version: "3"
services:
  aws-deployment-test:
    depends_on:
      - postgres
    build: . 
    environment:       
      PG_HOST: postgres
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  sut:
    build: . 
    depends_on:
      - aws-deployment-test
    environment:
      SERVICE_HOST: aws-deployment-test    
    command: npm run test