# version: '3'
# services:
#   web:
#     image: amazon/amazon-ecs-sample
#     ports:
#       - "80:80"
#     logging:
#       driver: awslogs
#       options: 
#         awslogs-group: cluster-100
#         awslogs-region: us-east-2
#         awslogs-stream-prefix: web


version: "3"
services:
  aws-deployment-test:
    # TODO: repositoryUri!!!
    #image: 403698577297.dkr.ecr.us-east-2.amazonaws.com/cluster-100 
    image: amazon/amazon-ecs-sample
    #container_name: aws-deployment-test
    #build: .
    # TODO: 8080
    ports:
      - "80:80"
    #depends_on:
      #- postgres
    environment:       
      PG_HOST: postgres
    logging:
      driver: awslogs
      options: 
        awslogs-group: cluster-100
        awslogs-region: us-west-2
        awslogs-stream-prefix: aws-deployment-test
  postgres:
    #container_name: postgres
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messages-manager